In [1]:
import numpy as np

In [2]:
n = 6
d = np.square(np.random.normal(size=(n,n)))
d = np.multiply(d,d.T)
np.fill_diagonal(d,0)

In [3]:
def NJ(d):
    
    edges = {}
    v_to_join = list(range(len(d)))
    n = len(v_to_join)
    delta = np.zeros(((2*n)-2,(2*n)-2))
    delta[:n,:n] = np.array(d)
    
    for _ in range(len(d)-2):
        
        # construct Q
        n = len(v_to_join)
        d0 = np.array(delta[v_to_join,:])
        d0 = d0[:,v_to_join]
        Q = ((n-2)*d0 - np.sum(d0,0)).T - np.sum(d0,1)
        np.fill_diagonal(Q,0)
        
        # select vertices to join
        vs0 = np.unravel_index(np.argmin(Q),Q.shape)
        vs = tuple([v_to_join[v] for v in vs0])
        print(Q)
        
        # add and remove vertices as needed 
        new_node = max(v_to_join)+1
        v_to_join.append(new_node)
        for v in vs:
            v_to_join.remove(v)
            
        # recalculate distances
        delta[vs[0],new_node] = 0.5*d0[vs0[0],vs0[1]] + (1.0/(2*(n-2)))*(sum(d0[vs0[0],:]) - sum(d0[vs0[1],:]))
        delta[new_node,vs[0]] = delta[vs[0],new_node]
        edges[(vs[0],new_node)] = delta[vs[0],new_node]
        
        delta[vs[1],new_node] = delta[vs[0],vs[1]] - delta[vs[0],new_node]
        delta[new_node,vs[1]] = delta[vs[1],new_node]
        edges[(vs[1],new_node)] = delta[vs[1],new_node]
        
        for node in v_to_join:
            
            if node != vs[0] and node != vs[1]:
                
                delta[node,new_node] = 0.5*(delta[vs[0],node] + delta[vs[1],node] - delta[vs[0],vs[1]])
                delta[new_node,node] = delta[node,new_node]
        
        # if we are done, find the last edge length
        if len(v_to_join) == 2:
            leftover_node = 3 - vs0[0] - vs0[1] 
            edges[(tuple(v_to_join))] = d0[vs0[0],leftover_node] - delta[vs[0],new_node]
    
    return delta,edges

In [4]:
NJ(d)

[[  0.          -0.76953611  -1.71065906 -12.79655713 -11.82741005
   -2.08619161]
 [ -0.76953611   0.          -3.07774273  -9.24463962 -13.00896977
   -3.08946574]
 [ -1.71065906  -3.07774273   0.         -14.04054713  -9.23893054
   -1.1224745 ]
 [-12.79655713  -9.24463962 -14.04054713   0.          17.33428422
  -10.4428943 ]
 [-11.82741005 -13.00896977  -9.23893054  17.33428422   0.
  -12.44932781]
 [ -2.08619161  -3.08946574  -1.1224745  -10.4428943  -12.44932781
    0.        ]]
[[ 0.         -0.41643334 -6.1576218  -1.30929827 -7.24932632]
 [-0.41643334  0.         -6.77068735 -1.78864964 -6.15690939]
 [-6.1576218  -6.77068735  0.         -6.25632919  4.05195862]
 [-1.30929827 -1.78864964 -6.25632919  0.         -5.77840262]
 [-7.24932632 -6.15690939  4.05195862 -5.77840262  0.        ]]
[[ 0.         -3.40409381 -0.91307496 -3.14691473]
 [-3.40409381  0.         -3.14691473 -0.91307496]
 [-0.91307496 -3.14691473  0.         -3.40409381]
 [-3.14691473 -0.91307496 -3.40409381  0

(array([[ 0.00000000e+00,  3.68718993e-01,  3.72568100e-02,
          1.04640714e-01,  9.64907137e-04,  1.26637619e-03,
          6.98783173e-02, -1.06127819e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 3.68718993e-01,  0.00000000e+00,  1.65013631e-04,
          1.29729921e+00,  1.02540982e-02,  5.51269624e-02,
          6.47661668e-01,  4.73251172e-01, -5.81707337e-01,
          0.00000000e+00],
        [ 3.72568100e-02,  1.65013631e-04,  0.00000000e+00,
          2.14088906e-03,  8.56582461e-01,  4.50693330e-01,
         -1.41835877e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 1.04640714e-01,  1.29729921e+00,  2.14088906e-03,
          0.00000000e+00,  1.03387446e+01,  9.59446797e-01,
          1.42049965e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 9.64907137e-04,  1.02540982e-02,  8.56582461e-01,
          1.03387446e+01,  0.00000000e+00,  1.11875847e-01,
          5.59659307e+00,  2.76383983e+00,  5.919614

In [5]:
print(d)

[[0.00000000e+00 3.68718993e-01 3.72568100e-02 1.04640714e-01
  9.64907137e-04 1.26637619e-03]
 [3.68718993e-01 0.00000000e+00 1.65013631e-04 1.29729921e+00
  1.02540982e-02 5.51269624e-02]
 [3.72568100e-02 1.65013631e-04 0.00000000e+00 2.14088906e-03
  8.56582461e-01 4.50693330e-01]
 [1.04640714e-01 1.29729921e+00 2.14088906e-03 0.00000000e+00
  1.03387446e+01 9.59446797e-01]
 [9.64907137e-04 1.02540982e-02 8.56582461e-01 1.03387446e+01
  0.00000000e+00 1.11875847e-01]
 [1.26637619e-03 5.51269624e-02 4.50693330e-01 9.59446797e-01
  1.11875847e-01 0.00000000e+00]]
